# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 430)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)

        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(480, 100, 230, 250))

        self.calcLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.calcLayout.setContentsMargins(0, 0, 0, 0)

        self.putRho = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.putRho.setAlignment(QtCore.Qt.AlignCenter)
        self.putRho.setReadOnly(True)
        self.calcLayout.addWidget(self.putRho, 5, 2, 1, 1)

        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_22, 6, 0, 1, 1)

        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_15, 0, 1, 1, 1)

        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_24, 8, 0, 1, 1)

        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_23, 7, 0, 1, 1)

        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.calcLayout.addWidget(self.label_17, 4, 0, 1, 1)

        self.callPrice = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.callPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.callPrice.setReadOnly(True)
        self.calcLayout.addWidget(self.callPrice, 1, 1, 1, 1)

        self.d1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.d1.setAlignment(QtCore.Qt.AlignCenter)
        self.d1.setReadOnly(True)
        self.calcLayout.addWidget(self.d1, 7, 1, 1, 2)

        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_19, 3, 0, 1, 1)

        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_16, 0, 2, 1, 1)

        self.callTheta = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.callTheta.setAlignment(QtCore.Qt.AlignCenter)
        self.callTheta.setReadOnly(True)
        self.calcLayout.addWidget(self.callTheta, 6, 1, 1, 1)

        self.callDelta = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.callDelta.setAlignment(QtCore.Qt.AlignCenter)
        self.callDelta.setReadOnly(True)
        self.calcLayout.addWidget(self.callDelta, 2, 1, 1, 1)

        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_21, 5, 0, 1, 1)

        self.gamma = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.gamma.setAlignment(QtCore.Qt.AlignCenter)
        self.gamma.setReadOnly(True)
        self.calcLayout.addWidget(self.gamma, 3, 1, 1, 2)

        self.putTheta = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.putTheta.setAlignment(QtCore.Qt.AlignCenter)
        self.putTheta.setReadOnly(True)
        self.calcLayout.addWidget(self.putTheta, 6, 2, 1, 1)

        self.vega = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.vega.setAlignment(QtCore.Qt.AlignCenter)
        self.vega.setReadOnly(True)
        self.calcLayout.addWidget(self.vega, 4, 1, 1, 2)

        self.d2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.d2.setAlignment(QtCore.Qt.AlignCenter)
        self.d2.setReadOnly(True)
        self.calcLayout.addWidget(self.d2, 8, 1, 1, 2)

        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_18, 1, 0, 1, 1)

        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_14, 0, 0, 1, 1)

        self.putDelta = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.putDelta.setAlignment(QtCore.Qt.AlignCenter)
        self.putDelta.setReadOnly(True)
        self.calcLayout.addWidget(self.putDelta, 2, 2, 1, 1)

        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.calcLayout.addWidget(self.label_20, 2, 0, 1, 1)

        self.putPrice = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.putPrice.setAlignment(QtCore.Qt.AlignCenter)
        self.putPrice.setReadOnly(True)
        self.calcLayout.addWidget(self.putPrice, 1, 2, 1, 1)

        self.callRho = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.callRho.setAlignment(QtCore.Qt.AlignCenter)
        self.callRho.setReadOnly(True)
        self.calcLayout.addWidget(self.callRho, 5, 1, 1, 1)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(270, 40, 190, 330))

        self.inputsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.inputsLayout.setContentsMargins(0, 0, 0, 0)

        self.spotLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.spotLabel)

        self.spotPrice = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.spotPrice)

        self.strikeLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.strikeLabel)

        self.strikePrice = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.strikePrice)

        self.riskFreeRateLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.riskFreeRateLabel)

        self.riskFreeRate = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.riskFreeRate)

        self.divYieldLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.divYieldLabel)

        self.divYield = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.divYield)

        self.startLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.startLabel)

        self.startDate = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.startDate.setCalendarPopup(True)
        self.startDate.setDate(datetime.date.today())
        self.inputsLayout.addWidget(self.startDate)
        
        self.expLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.expLabel)
        
        self.expDate = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.expDate.setCalendarPopup(True)
        self.expDate.setDate(datetime.date.today() + datetime.timedelta(days=30))
        self.inputsLayout.addWidget(self.expDate)
        
        self.volatilityLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.volatilityLabel)

        self.volatility = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.inputsLayout.addWidget(self.volatility)

        self.infoText = QtWidgets.QTextBrowser(self.centralwidget)
        self.infoText.setGeometry(QtCore.QRect(20, 220, 230, 190))
        # self.infoText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        # self.infoText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        self.divHead = QtWidgets.QLabel(self.centralwidget)
        self.divHead.setGeometry(QtCore.QRect(20, 10, 230, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.divHead.setFont(font)
        
        self.inputsHead = QtWidgets.QLabel(self.centralwidget)
        self.inputsHead.setGeometry(QtCore.QRect(270, 10, 190, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inputsHead.setFont(font)

        self.calculationsHead = QtWidgets.QLabel(self.centralwidget)
        self.calculationsHead.setGeometry(QtCore.QRect(480, 70, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.calculationsHead.setFont(font)
        
        self.calculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(270, 380, 190, 30))
        
        self.divAllDeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.divAllDeleteButton.setGeometry(QtCore.QRect(20, 180, 230, 24))
        
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 80, 230, 90))
        
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        
        self.divDeleteButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.gridLayout.addWidget(self.divDeleteButton, 0, 2, 1, 1)

        self.divAddButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.gridLayout.addWidget(self.divAddButton, 2, 0, 1, 3)

        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)

        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.divPayment = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.gridLayout.addWidget(self.divPayment, 1, 0, 1, 1)

        self.divDate = QtWidgets.QDateEdit(self.gridLayoutWidget_2)
        self.divDate.setCalendarPopup(True)
        self.divDate.setDate(datetime.date.today() + datetime.timedelta(days=1))
        self.gridLayout.addWidget(self.divDate, 1, 1, 1, 2)

        self.divBox = QtWidgets.QComboBox(self.centralwidget)
        self.divBox.setGeometry(QtCore.QRect(20, 40, 230, 25))

        self.undHead = QtWidgets.QLabel(self.centralwidget)
        self.undHead.setGeometry(QtCore.QRect(480, 10, 230, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.undHead.setFont(font)
        
        self.undTypeBox = QtWidgets.QComboBox(self.centralwidget)
        self.undTypeBox.setGeometry(QtCore.QRect(480, 40, 231, 25))
        
        self.undTypeBox.addItem("Equity")
        self.undTypeBox.addItem("Currency")
        self.undTypeBox.addItem("Index")
        self.undTypeBox.addItem("Future")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Black Scholes Option Calculator"))
        self.label_22.setText(_translate("MainWindow", "Theta, Θ"))
        self.label_15.setText(_translate("MainWindow", "Call"))
        self.label_24.setText(_translate("MainWindow", "d2"))
        self.label_23.setText(_translate("MainWindow", "d1"))
        self.label_17.setText(_translate("MainWindow", "Vega, v"))
        self.label_19.setText(_translate("MainWindow", "Gamma, Γ"))
        self.label_16.setText(_translate("MainWindow", "Put"))
        self.label_21.setText(_translate("MainWindow", "Rho, ρ"))
        self.label_18.setText(_translate("MainWindow", "Price"))
        self.label_14.setText(_translate("MainWindow", "Option"))
        self.label_20.setText(_translate("MainWindow", "Delta, Δ"))
        self.spotLabel.setText(_translate("MainWindow", "Spot Price, S"))
        self.spotPrice.setPlaceholderText(_translate("MainWindow", "$25,00"))
        self.strikeLabel.setText(_translate("MainWindow", "Strike Price, K"))
        self.strikePrice.setPlaceholderText(_translate("MainWindow", "$30,00"))
        self.riskFreeRateLabel.setText(_translate("MainWindow", "Risk-free Rate, r"))
        self.riskFreeRate.setPlaceholderText(_translate("MainWindow", "2,50%"))
        self.divYieldLabel.setText(_translate("MainWindow", "Dividend Yield, q"))
        self.divYield.setPlaceholderText(_translate("MainWindow", "2,50%"))
        self.startLabel.setText(_translate("MainWindow", "Start Date, t"))
        self.expLabel.setText(_translate("MainWindow", "Expiration Date, T"))
        self.volatilityLabel.setText(_translate("MainWindow", "Volatility, σ"))
        self.volatility.setPlaceholderText(_translate("MainWindow", "26,07%"))
        self.infoText.setPlaceholderText(_translate("MainWindow", "Info about option..."))
        self.divHead.setText(_translate("MainWindow", "Dividend payments"))
        self.inputsHead.setText(_translate("MainWindow", "Inputs"))
        self.calculationsHead.setText(_translate("MainWindow", "Calculations"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))
        self.divAllDeleteButton.setText(_translate("MainWindow", "Delete all dividend payments"))
        self.divDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.divAddButton.setText(_translate("MainWindow", "Add new payment"))
        self.label_4.setText(_translate("MainWindow", "Date"))
        self.label_2.setText(_translate("MainWindow", "Edit / Add payment"))
        self.divPayment.setPlaceholderText(_translate("MainWindow", "$1,52"))
        self.undHead.setText(_translate("MainWindow", "Underlying type"))
        
